/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type FirmwareStatus = "available" | "downloading" | "installed" | "installing";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type InteractionType = "alert" | "command" | "description" | "question";

export type SpeechRate = "fast" | "normal" | "slow";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export type VisionMode = "full" | "smart";

export type VoiceType = "feminine" | "masculine";

export interface FirmwareVersions {
  changelog: string;
  createdAt: Generated<Timestamp>;
  id: string;
  installedAt: Timestamp | null;
  releaseDate: Timestamp;
  sizeMb: number;
  status: Generated<FirmwareStatus>;
  version: string;
}

export interface Interactions {
  confidence: number | null;
  createdAt: Generated<Timestamp>;
  id: string;
  mode: VisionMode;
  systemResponse: string;
  type: InteractionType;
  userInput: string | null;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean>;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp>;
  userId: number;
}

export interface Settings {
  alertPriority: Generated<boolean>;
  audioVolume: Generated<number>;
  confidenceThreshold: Generated<number>;
  defaultVisionMode: Generated<VisionMode>;
  headRotationThreshold: Generated<number>;
  id: Generated<string>;
  speechRate: Generated<SpeechRate>;
  updatedAt: Generated<Timestamp>;
  updateIntervalMs: Generated<number>;
  vibrationFeedback: Generated<boolean>;
  voiceType: Generated<VoiceType>;
}

export interface UserPasswords {
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
}

export interface DB {
  firmwareVersions: FirmwareVersions;
  interactions: Interactions;
  loginAttempts: LoginAttempts;
  sessions: Sessions;
  settings: Settings;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const VisionModeArrayValues: [VisionMode, ...VisionMode[]] = ["full","smart"];
export const InteractionTypeArrayValues: [InteractionType, ...InteractionType[]] = ["alert","command","description","question"];
export const SpeechRateArrayValues: [SpeechRate, ...SpeechRate[]] = ["fast","normal","slow"];
export const VoiceTypeArrayValues: [VoiceType, ...VoiceType[]] = ["feminine","masculine"];
export const FirmwareStatusArrayValues: [FirmwareStatus, ...FirmwareStatus[]] = ["available","downloading","installed","installing"];
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.