/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */
// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const VisionModeArrayValues = ["full", "smart"];
export const InteractionTypeArrayValues = ["alert", "command", "description", "question"];
export const SpeechRateArrayValues = ["fast", "normal", "slow"];
export const VoiceTypeArrayValues = ["feminine", "masculine"];
export const FirmwareStatusArrayValues = ["available", "downloading", "installed", "installing"];
export const UserRoleArrayValues = ["admin", "user"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.
